### ISSUE TITLE
Getting InvalidArgumentException with overviewFormat

### ISSUE THREAD

**Issue by Anahkiasen** [robinvdvleuten/php-nntp#13]
I'm using a custom command to fetch the BODY of an article:

```php
class Body extends Command
{
    /**
     * @var integer
     */
    const BODY_RECEIVED = 222;

    /**
     * @var integer
     */
    const NO_SUCH_ARTICLE = 423;

    /**
     * @var string
     */
    private $article;

    /**
     * Constructor
     *
     * @param string $article The name of the group.
     */
    public function __construct($article)
    {
        $this->article = $article;

        parent::__construct([], true);
    }

    /**
     * @return string
     */
    public function execute()
    {
        return sprintf('BODY %s', $this->article);
    }

    /**
     * @return array
     */
    public function getExpectedResponseCodes()
    {
        return [
            self::BODY_RECEIVED   => 'onBodyReceived',
            self::NO_SUCH_ARTICLE => 'onArticleNotFound',
        ];
    }

    /**
     * @param MultiLineResponseInterface $response
     */
    public function onBodyReceived(MultiLineResponseInterface $response)
    {
        // Convert to array and remove encoding lines
        $body = (array) $response->getLines();
        $body = implode(PHP_EOL, $body);

        $this->result = trim($body);
    }

    /**
     * @param ResponseInterface $response
     */
    public function onArticleNotFound(ResponseInterface $response)
    {
        $this->result = $response->getMessage();
    }
}
```

However when I call `$client->overviewFormat()->getResult()` after calling this command I inevitably get the following:

```
PHP Fatal error:  Uncaught exception 'Rvdv\Nntp\Exception\InvalidArgumentException' with message 'Invalid response given: "> >"' in /Users/anahkiasen/Sites/anahkiasen/rfc-history/vendor/rvdv/nntp/src/Response/Response.php:62
Stack trace:
#0 /Users/anahkiasen/Sites/anahkiasen/rfc-history/vendor/rvdv/nntp/src/Connection/Connection.php(157): Rvdv\Nntp\Response\Response::createFromString('> >\r\n')
#1 /Users/anahkiasen/Sites/anahkiasen/rfc-history/vendor/rvdv/nntp/src/Connection/Connection.php(108): Rvdv\Nntp\Connection\Connection->getResponse()
#2 /Users/anahkiasen/Sites/anahkiasen/rfc-history/vendor/rvdv/nntp/src/Client.php(171): Rvdv\Nntp\Connection\Connection->sendCommand(Object(Rvdv\Nntp\Command\OverviewFormatCommand))
#3 /Users/anahkiasen/Sites/anahkiasen/rfc-history/vendor/rvdv/nntp/src/Client.php(131): Rvdv\Nntp\Client->sendCommand(Object(Rvdv\Nntp\Command\OverviewFormatCommand))
#4 /Users/anahkiasen/Sites/anahkiasen/rfc-history/test.php(15): Rvdv\Nntp\Client->overviewFormat()
#5 {main}
  thrown in /Users/anahkiasen/Sites/anahkiasen/rfc-history/vendor/rvdv/nntp/src/Response/Response.php on line 62
```

This code per example fails every time:

```php
<?php
use History\Services\Internals\Commands\Body;
use Rvdv\Nntp\Client;
use Rvdv\Nntp\Connection\Connection;

require 'vendor/autoload.php';

$connection = new Connection('news.php.net', 119);
$client     = new Client($connection);
$client->connect();

$client->group('php.internals');
$article = $client->sendCommand(new Body(88855))->getResult();
$format  = $client->overviewFormat()->getResult();
```

While the contents is nonetheless properly fetched and `$article` holds the right value.

**Comment by Anahkiasen** [comment]
Issue seems to be coming from `Connection::getMultiLineResponse` where this is done:

```
if (".\r\n" === substr($buffer, -3)) {
    break;
}
```

This is truncating heavily the responses, sometimes to the point of corrupting the data. This is the truncated output that gets returned from the stream:

```
>>> $app->get('History\Services\Internals\Internals')->getArticleBody(40093);
=> """
   Hi,\n
   \n
   I updated the RFC.
   """
```

If I comment out the `break;` this is what I get:

```
```

Any reason you're stopping the stream as soon as you encounter `".\r\n"`? Seems like this makes php-nntp stop streaming the response as soon as someone ends a sentence with a period and go to the next line

**Comment by Anahkiasen** [comment]
Ok I understand the break now. I fixed it like that personally:

```php
if ("\n.\r\n" === substr($buffer, -4)) {
  break;
}
```

Because then we're sure it's a period on a new-line to mark the end of the content and not a real period. Works for me as far as I can see
